(()=>{
 'use strict';
 const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');
 if(menu&&nav){const close=()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open')};menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){close();menu.focus()}});nav.addEventListener('click',e=>{if(e.target.closest('a'))close()});window.addEventListener('resize',()=>{if(window.innerWidth>900)close()})}
 const form=document.getElementById('quote-form');
 document.querySelectorAll('[data-contact-form]').forEach(f=>f.addEventListener('submit',()=>{f.querySelector('.form-status').textContent='Bitte schliessen Sie die geschützte Übermittlung ab.'}));
 if(!form)return;
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF'}).format(n);
 const service=$('service'),pack=$('package'),budget=$('budget'),accept=$('accept-offer'),send=$('send-offer');
 const dates=[1,2,3].map(n=>$('date-'+n));const now=new Date();const today=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);dates.forEach(d=>d.min=today);
 const param=new URLSearchParams(location.search).get('leistung');if(DGSPrice.packages[param])service.value=param;
 let result,urls=[];
 function packages(){pack.replaceChildren();DGSPrice.packages[service.value].forEach(([key,label])=>{const o=document.createElement('option');o.value=key;o.textContent=label;pack.append(o)})}
 function photos(){const files=[...form.querySelectorAll('[data-photo]')];const chosen=files.flatMap(i=>i.files?.length?[i.files[0]]:[]);const error=chosen.some(f=>!['image/jpeg','image/png'].includes(f.type))?'Bitte nur JPG- oder PNG-Fotos auswählen.':chosen.reduce((s,f)=>s+f.size,0)>9*1024*1024?'Die Fotos dürfen zusammen höchstens 9 MB gross sein.':'';files.forEach(i=>i.setCustomValidity(error));$('photo-error').textContent=error;return !error}
 function summary(){return ['Angebotsanfrage – Dampfglanzservice-Ademi','Preisregel: '+result.version,'Leistung: '+service.options[service.selectedIndex].text+' / '+result.label,'Gesamtpreis: '+money(result.proposal),'Enthalten: '+result.scope,'Standort Rorschach; keine separaten Zusatzarbeiten.','Kundenbudget: '+money(Number(budget.value)),'Terminvorschläge: '+dates.map(d=>d.value).filter(Boolean).join(', '),'Zeitfenster: '+$('time-window').value,'Auftrag und Termin erst nach persönlicher Bestätigung.'].join('\n')}
 function update(invalidate=true){validateDates();if(invalidate)accept.checked=false;result=DGSPrice.calculate(service.value,pack.value,budget.value,$('condition').value);budget.setCustomValidity(result.valid?'':result.error);const selected=DGSPrice.packages[service.value].find(p=>p[0]===pack.value);$('scope').textContent=selected?.[3]||'';$('result-service').textContent=service.options[service.selectedIndex].text+' · '+(selected?.[1]||'');$('result-price').textContent=result.valid?money(result.proposal):(budget.value===''?'Budget eingeben':'Budget prüfen');$('budget-notice').textContent=result.valid?'Ihr Angebotspreis ist berechnet.':(budget.value===''?'Bitte geben Sie Ihr Budget ein.':result.error);$('result-note').textContent=result.valid?result.scope:'Für Sonderfälle erhalten Sie eine persönliche Offerte.';$('quote-summary').value=result.valid?summary():'';$('print-quote').disabled=!result.valid;send.disabled=!result.valid||!accept.checked;}
 service.addEventListener('change',()=>{packages();update()});
 form.addEventListener('input',e=>{update(e.target!==accept)});form.addEventListener('change',e=>{if(e.target.matches('[data-photo]')){urls.forEach(URL.revokeObjectURL);urls=[];$('photo-preview').replaceChildren();if(photos())[...form.querySelectorAll('[data-photo]')].forEach(input=>{if(!input.files.length)return;const figure=document.createElement('figure'),image=document.createElement('img'),caption=document.createElement('figcaption'),remove=document.createElement('button');const f=input.files[0],url=URL.createObjectURL(f);urls.push(url);image.src=url;image.alt='Foto-Vorschau';caption.textContent=f.name;remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Foto entfernen');remove.onclick=()=>{input.value='';input.dispatchEvent(new Event('change',{bubbles:true}))};figure.append(image,remove,caption);$('photo-preview').append(figure)})}update(e.target!==accept)});
 function validateDates(){dates.forEach(d=>d.setCustomValidity(''));const chosen=dates.filter(d=>d.value);for(const d of chosen){if(d.value<today)d.setCustomValidity('Bitte einen zukünftigen Termin wählen.');else if(chosen.filter(x=>x.value===d.value).length>1)d.setCustomValidity('Bitte unterschiedliche Termine auswählen.')}}
 form.addEventListener('submit',e=>{update(false);validateDates();if(!result.valid||!accept.checked||!photos()||!form.checkValidity()){e.preventDefault();form.reportValidity();return}$('quote-summary').value=summary();$('quote-status').textContent='Bitte schliessen Sie die Übermittlung ab. Der Auftrag und Termin werden danach persönlich bestätigt.';});
 $('print-quote').onclick=()=>{update(false);if(!result.valid)return;const area=$('print-summary');area.replaceChildren();const h=document.createElement('h1');h.textContent='Ihre Angebotsübersicht';const text=document.createElement('p');text.style.whiteSpace='pre-line';text.textContent=summary();area.append(h,text);window.print()};
 window.addEventListener('pagehide',()=>urls.forEach(URL.revokeObjectURL));packages();update();
})();
