from pathlib import Path
from html import escape as esc
import json
from PIL import Image,ImageOps
ROOT=Path(__file__).resolve().parents[1]
BASE='https://www.dampfglanzservice-ademi.ch'
NAME='Dampfglanzservice-Ademi'
regions={'goldach':'Goldach','rorschacherberg':'Rorschacherberg','arbon':'Arbon','steinach':'Steinach','horn':'Horn','thal':'Thal','staad':'Staad','rheineck':'Rheineck','st-margrethen':'St. Margrethen'}
services={
 'wohnungsreinigung':dict(label='Wohnungsreinigung',title='Mehr Zeit für Sie.\nMehr Glanz für Ihr Zuhause.',desc='Wohnungsreinigung in Rorschach und der Ostschweiz – einmalig oder regelmässig, mit einem Leistungsumfang, der zu Ihrem Alltag passt.',image='home',tag='Einmalig oder regelmässig',intro='Ein gepflegtes Zuhause, ohne dass Ihre Freizeit zu kurz kommt.',body='Wir reinigen Ihre Wohnung nach Absprache: von Böden und Oberflächen bis zu Küche und Bad. Gemeinsam legen wir fest, welche Räume und Arbeiten wichtig sind und wie häufig Sie Unterstützung wünschen.',items=[('Küche','Arbeitsflächen, Spüle und zugängliche Oberflächen. Geräte innen nach Vereinbarung.'),('Bad & WC','Sanitäre Einrichtungen, Armaturen, Spiegel und zugängliche Flächen.'),('Wohnräume','Staub entfernen, Böden saugen und wischen, Oberflächen sorgfältig reinigen.'),('Nach Ihrem Bedarf','Fenster, schwer zugängliche Stellen und weitere Arbeiten vorab abstimmen.')],faq=[('Kann ich eine regelmässige Reinigung vereinbaren?','Ja. Häufigkeit, Aufgaben und Zugang zur Wohnung stimmen wir persönlich mit Ihnen ab.'),('Wie wird der Preis bestimmt?','Grösse, Zustand, Reinigungsumfang und Häufigkeit bestimmen die individuelle Offerte.'),('Muss ich während der Reinigung zu Hause sein?','Zugang und Schlüsselübergabe vereinbaren wir im Voraus. Teilen Sie uns besondere Hinweise zu Oberflächen oder Gegenständen mit.')]),
 'endreinigung-abnahmegarantie':dict(label='Endreinigung',title='Ein sauberer Abschluss.\nEin entspannter Umzug.',desc='Endreinigung mit vereinbarter Abgabegarantie in Rorschach und der Ostschweiz. Reinigung und Wohnungsabgabe persönlich abstimmen.',image='bath',tag='Mit vereinbarter Abgabegarantie',intro='Sie kümmern sich um den Umzug. Wir um die Reinigung.',body='Bei einer Wohnungsabgabe zählt der Blick fürs Detail. Wir vereinbaren den Reinigungsumfang und den Termin passend zur Übergabe. Auf Wunsch begleiten wir die Abgabe. Die Abgabegarantie gilt für die vereinbarten Reinigungsleistungen und wird in Ihrer Offerte festgehalten.',items=[('Küche & Geräte','Schränke, Backofen, Kühlschrank und weitere Geräte im vereinbarten Umfang.'),('Bad & Sanitär','Armaturen, Dusche, WC und zugängliche Flächen gründlich reinigen.'),('Räume & Fenster','Böden, Fenster, Rahmen und Storen nach Vereinbarung.'),('Wohnungsabgabe','Termin, Begleitung und Nachbesserung vereinbarter Reinigungsarbeiten vorab klären.')],faq=[('Was umfasst die Abgabegarantie?','Sie bezieht sich auf die vereinbarten und ausgeführten Reinigungsleistungen. Umfang und mögliche Nachbesserungen werden vor dem Auftrag schriftlich vereinbart.'),('Welche Angaben brauchen Sie für eine Offerte?','Adresse, Wohnfläche, Zimmerzahl, Zustand, Fotos und Abgabetermin. Angaben zu Fenstern, Storen und Geräten helfen bei der Planung.'),('Wann sollte ich anfragen?','Melden Sie sich, sobald der Abgabetermin feststeht. Die Terminverfügbarkeit bestätigen wir persönlich.')]),
 'autoreinigung':dict(label='Autoreinigung',title='Einsteigen.\nWieder wohlfühlen.',desc='Autoinnenreinigung mit Online-Offerte in Rorschach. Fahrzeug, Verschmutzung und Budget angeben, Fotos hinzufügen und Preisvorschlag erhalten.',image='car',tag='Innenraum sorgfältig gereinigt',intro='Frische für den Innenraum. Sorgfalt bis ins Detail.',body='Alltag, Kinder, Haustiere: Ein Auto erlebt viel. Wir reinigen Ihren Innenraum nach vereinbartem Umfang. Beschreiben Sie den Zustand und Ihre Wünsche – so können wir Aufwand und passende Leistungen vor dem Termin abstimmen.',items=[('Innenraum','Sichtbare und zugängliche Flächen, Ablagen und Fussraum nach Vereinbarung.'),('Sitze & Polster','Materialgerechte Reinigung; Flecken und empfindliche Materialien vorab beurteilen.'),('Tierhaare & Flecken','Besondere Verschmutzungen mit Fotos zeigen. Der Zusatzaufwand wird persönlich geprüft.'),('Weitere Wünsche','Kofferraum, Gerüche oder Aussenreinigung separat anfragen und abstimmen.')],faq=[('Wie funktioniert der Online-Preisvorschlag?','Wählen Sie ein Reinigungspaket und geben Sie Ihr Budget ein. Sie erhalten eine Angebotsübersicht mit Preis und enthaltenen Leistungen. Bestätigen Sie die Übersicht und nennen Sie zwei mögliche Termine. Wir bestätigen den Auftrag und Termin persönlich.'),('Kann ich Fotos schicken?','Ja. Im Offertenformular können Sie bis zu drei JPG- oder PNG-Fotos mit insgesamt maximal 9 MB hinzufügen. Sie werden erst beim Absenden übermittelt.'),('Werden die Fotos automatisch bewertet?','Nein. Sie geben den Verschmutzungsgrad selbst an. Wir prüfen Ihre Fotos persönlich und bestätigen den Leistungsumfang und Preis.'),('Wo findet die Reinigung statt?','Ort, Zugang und Termin werden persönlich mit Ihnen vereinbart. Eine allfällige Anfahrt ist im Online-Vorschlag nicht eingerechnet.')]),
 'polsterreinigung':dict(label='Polsterreinigung',title='Lieblingsplätze.\nFrisch gepflegt.',desc='Polsterreinigung für Sofas, Sessel und textile Flächen in Rorschach und der Ostschweiz. Material, Zustand und Umfang persönlich prüfen lassen.',image='polster',tag='Sofas · Sessel · Textile Flächen',intro='Eine sorgfältige Reinigung beginnt mit dem richtigen Blick auf das Material.',body='Textile Oberflächen brauchen eine passende Behandlung. Wir besprechen Material, Grösse, Zustand und Flecken, bevor wir den Reinigungsumfang festlegen. Fotos unterstützen die erste Einschätzung; die Eignung der Oberfläche wird vor der Reinigung geprüft.',items=[('Sofas & Sessel','Sitzflächen, Rückenlehnen und Armlehnen im vereinbarten Umfang.'),('Flecken','Art und Alter der Flecken mitteilen. Nicht jeder Fleck lässt sich vollständig entfernen.'),('Textile Flächen','Teppiche und weitere textile Flächen nach Material- und Eignungsprüfung.'),('Trocknung','Nutzungs- und Trocknungshinweise werden passend zur Behandlung besprochen.')],faq=[('Lassen sich alle Flecken entfernen?','Das hängt von Material, Fleckenart und bisherigen Behandlungen ab. Eine vollständige Entfernung können wir nicht pauschal zusagen.'),('Welche Angaben benötigen Sie?','Fotos, Anzahl und Grösse der Möbel, Material und eine Beschreibung der Verschmutzung. So erstellen wir eine passende Offerte.'),('Wann kann ich das Sofa wieder nutzen?','Die Trocknungszeit hängt von Material, Behandlung und Raumklima ab. Sie erhalten dazu Hinweise im Rahmen der Reinigung.')])}
# Optimised derivatives of existing business images, never fictional work examples.
for key,src in {'home':'wohn1.jpeg','bath':'wohn2.jpeg','car':'auto1.jpeg','bath-detail':'wohn7.jpeg','bath-before':'bad-vorher.png','bath-after':'bad-nachher.png','drawer-before':'vorher-kuechenschublade.png','drawer-after':'nachher-kuechenschublade.png','brand':'logo.png'}.items():
 target=ROOT/'assets'/f'{key}.webp'
 if not target.exists():
  im=ImageOps.exif_transpose(Image.open(ROOT/src)).convert('RGB');im.thumbnail((1400,1200));im.save(target,'WEBP',quality=84)

def img(key,alt,lazy=True):
 if key=='polster':
  im=Image.open(ROOT/'assets/polster.webp');w,h=im.size;ext='webp'
 else:
  im=Image.open(ROOT/'assets'/f'{key}.webp');w,h=im.size;ext='png' if key=='brand' else 'webp'
 return f'<img src="/assets/{key}.{ext}" alt="{esc(alt)}" width="{w}" height="{h}" '+('loading="lazy" decoding="async"' if lazy else 'fetchpriority="high"')+'>'
def button(text,url='/offerte/',secondary=False):return f'<a class="button {"secondary" if secondary else "primary"}" href="{url}">{text} <span aria-hidden="true">↗</span></a>'
def header(path):
 nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if path==url else '')+f'>{label}</a>' for url,label in [('/leistungen/','Leistungen'),('/regionen/','Regionen'),('/ueber-uns/','Über uns'),('/kontakt/','Kontakt')])
 return f'''<a class="skip" href="#main">Zum Inhalt</a><header class="header"><div class="container header-inner"><a class="brand" href="/" aria-label="Dampfglanzservice-Ademi – Startseite">{img('brand','',False)}<span>DAMPFGLANZSERVICE<span class="brand-sub">ADEMI <i>•</i> REINIGUNG</span></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menü <span aria-hidden="true">☰</span></button><nav id="main-nav" aria-label="Hauptnavigation">{nav}<a class="nav-offerte" href="/offerte/">Online-Offerte ↗</a></nav>{button('Offerte anfragen')}</div></header>'''

def quick_contact():
 return '<nav class="quick-contact" aria-label="Direktkontakt"><a class="quick-whatsapp" href="https://wa.me/41765024998" target="_blank" rel="noopener" aria-label="WhatsApp an Dampfglanzservice-Ademi"><svg class="whatsapp-mark" viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 3a13 13 0 0 0-11.2 19.6L3 29l6.6-1.7A13 13 0 1 0 16 3Zm0 2.4a10.6 10.6 0 1 1-5.7 19.5l-.5-.3-3.4.9.9-3.3-.3-.5A10.6 10.6 0 0 1 16 5.4Z"/><path fill="currentColor" d="M11.1 9.5c-.4 0-.7.2-1 .5-.6.7-.9 1.4-.8 2.4.2 2.7 2.7 6.6 6.7 8.3 2 .9 3.4.9 4.3.3.7-.5 1.1-1.3 1.2-2.1 0-.3-.1-.5-.4-.6l-2.8-1.3c-.3-.1-.5 0-.7.2l-1.1 1.3c-.2.2-.4.3-.7.1-1.9-.9-3.2-2.1-4.2-3.9-.2-.3-.1-.5.1-.7l.9-1.1c.2-.2.3-.5.1-.8l-1.2-2.4c-.1-.2-.3-.3-.6-.3Z"/></svg><span>WhatsApp</span></a><a class="quick-call" href="tel:+41765024998" aria-label="Dampfglanzservice-Ademi anrufen: +41 76 502 49 98"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3 3 5c0 8 8 16 16 16l2-2-4-5-3 2-6-6 2-3Z"/></svg><span>Anrufen</span></a></nav>'
def reviews_grid():
 data=json.loads((ROOT/'tools/reviews.json').read_text())
 return '<div class="review-grid">'+''.join('<article class="review-card"><div class="review-stars" aria-label="5 von 5 Sternen">★★★★★</div><h3>'+esc(r['name'])+'</h3><p class="review-date">Google: '+esc(r['date'])+' · geprüft am 09.10.2026</p>'+('<blockquote>„'+esc(r['excerpt'])+'“</blockquote><span class="small-label">Kurzer Originalauszug</span>' if r['excerpt'] else '<p>Bewertung ohne Rezensionstext.</p>')+'<a class="text-link" href="https://www.google.com/maps/contrib/'+r['author']+'/reviews?hl=de-CH" target="_blank" rel="noopener">Original auf Google ↗</a></article>' for r in data['items'])+'</div>'
def reviews_page():
 return breadcrumbs('Kundenbewertungen')+hero('Echte Stimmen · Google','Ihre Erfahrung.<br>Unser Ansporn.','Alle elf im Google-Profil sichtbaren Bewertungen, geprüft am 9. Oktober 2026. Die kurzen Originalauszüge sind gekennzeichnet. Vollständige Rezensionen finden Sie über die Quellenlinks.')+'<section class="section"><div class="container"><div class="review-explainer"><h2>5,0 von 5 bei 11 Bewertungen.</h2><p>Die Zeitangaben entsprechen der Google-Anzeige am Prüfdatum. Es werden keine genauen Kalendertage aus relativen Angaben berechnet. Diese Momentaufnahme aktualisiert sich nicht automatisch.</p>'+button('Alle Rezensionen im Unternehmensprofil','https://share.google/dCGFMFzPosnnV46j6',True)+'</div>'+reviews_grid()+'</div></section>'+cta()
def profile_section():
 return '<section class="section profile-section"><div class="container content-split"><div><span class="eyebrow">Persönlich. Nachprüfbar.</span><h2>Das sagen unsere<br>Kundinnen und Kunden.</h2><div class="google-rating"><span aria-hidden="true">★★★★★</span><strong>5,0 / 5</strong><p>11 Bewertungen auf Google · Stand 9. Oktober 2026</p></div><p>Lesen Sie die Kundenbewertungen direkt in unserem Google-Unternehmensprofil und sehen Sie weitere Bilder unserer Arbeit.</p><div class="hero-actions">'+button('Kundenbewertungen ansehen','/bewertungen/',True)+'</div></div><div class="profile-card"><span class="small-label">Dampfglanzservice-Ademi</span><h3>Ihr direkter Ansprechpartner.</h3><p>Trischlistrasse 25 · 9400 Rorschach<br>Wohnungs-, End-, Auto- und Polsterreinigung</p><p>Besprechen Sie Ihren Auftrag direkt mit uns. Wir klären Leistungen, Preis und Termin vor der Ausführung.</p>'+button('Auf WhatsApp schreiben','https://wa.me/41765024998')+'</div></div></section>'

def footer():
 links=''.join(f'<a href="/{key}/">{s["label"]}</a>' for key,s in services.items())
 return f'''<footer><div class="container footer-grid"><div><a class="footer-brand" href="/">Dampfglanzservice<span>Ademi.</span></a><p>Saubere Arbeit. Persönlicher Service.<br>In Rorschach und der Ostschweiz.</p><span class="footer-location">9400 Rorschach · Schweiz</span></div><div><h2>Unsere Leistungen</h2>{links}<a href="/offerte/">Online-Offerte</a></div><div><h2>Direkt erreichen</h2><a href="tel:+41765024998">+41 76 502 49 98</a><a href="mailto:info@dampfglanzservice-ademi.ch">info@dampfglanzservice-ademi.ch</a><p>Trischlistrasse 25<br>9400 Rorschach</p></div><div><h2>Gut zu wissen</h2><a href="/reinigungsprojekte/">Einblicke in unsere Arbeit</a><a href="/bewertungen/">Kundenbewertungen</a><a href="/regionen/">Unser Einsatzgebiet</a><a href="/ueber-uns/">Über uns</a><a href="/kontakt/">Kontakt</a><a href="/impressum/">Impressum</a><a href="/datenschutz/">Datenschutz</a></div></div><div class="container footer-bottom"><span>© 2026 Dampfglanzservice-Ademi</span><span>UID CHE-199.157.071</span><a href="#top">Nach oben ↑</a></div></footer>'''
def section_head(kicker,title,text='',link=''):
 return f'<div class="section-head"><div><span class="eyebrow">{kicker}</span><h2>{title}</h2>'+ (f'<p>{text}</p>' if text else '')+f'</div>{link}</div>'
def hero(kicker,title,desc,key=None,cta='Offerte anfragen',url='/offerte/'):
 visual=f'<div class="hero-visual">{img(key,"Sofa aus dem Unternehmensprofil von Dampfglanzservice-Ademi" if key=="polster" else "Reinigungsprojekt von Dampfglanzservice-Ademi",False)}<div class="image-caption"><span>Mit Sorgfalt bis ins Detail.</span><span aria-hidden="true">↗</span></div></div>' if key else ''
 return f'<section class="hero {"text-hero" if not key else ""}"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow"><i></i>{kicker}</span><h1>{title.replace(chr(10),"<br>")}</h1><p>{desc}</p><div class="hero-actions">{button(cta,url)}{button("Persönlich beraten lassen","tel:+41765024998",True)}</div><div class="hero-assurance"><span>✓ Persönlicher Kontakt</span><span>✓ Unverbindliche Anfrage</span></div></div>{visual}</div></section>'
def cards():
 return '<div class="service-grid">'+''.join(f'<a class="service-card" href="/{key}/"><div class="service-image">{img(s["image"],"Sofa aus unserem Unternehmensprofil" if key=="polsterreinigung" else s["label"]+" – Einblick in unsere Arbeit")}<span class="card-index">0{i+1}</span></div><div class="service-card-body"><span class="small-label">{s["tag"]}</span><h3>{s["label"]} <span aria-hidden="true">↗</span></h3><p>{s["intro"]}</p></div></a>' for i,(key,s) in enumerate(services.items()))+'</div>'
def process():
 return '<section class="section"><div class="container">'+section_head('Einfach. Persönlich. Klar.','In drei Schritten zu mehr Glanz.')+'<div class="steps">'+''.join(f'<article><span class="step-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate([('Wünsche beschreiben','Leistung auswählen, Zustand beschreiben und bei Bedarf Fotos hinzufügen.'),('Offerte abstimmen','Wir prüfen Ihre Angaben und vereinbaren Preis, Umfang und Termin mit Ihnen.'),('Sauberkeit geniessen','Wir führen die vereinbarten Arbeiten sorgfältig aus. Sie haben wieder Zeit für anderes.')]))+'</div></div></section>'
def faq(items):
 return '<section class="section faq-section"><div class="container faq-layout"><div><span class="eyebrow">Gut zu wissen</span><h2>Ihre Fragen.<br>Unsere Antworten.</h2><p>Noch etwas offen? Wir sind persönlich für Sie da.</p><a class="text-link" href="/kontakt/">Kontakt aufnehmen ↗</a></div><div class="faq-list">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in items)+'</div></div></section>'
def cta():return f'<section class="cta-section"><div class="container cta-inner"><div><span class="eyebrow">Der nächste Schritt ist einfach.</span><h2>Was dürfen wir<br>für Sie sauber machen?</h2></div><div><p>Erzählen Sie uns von Ihrem Auftrag.<br>Wir kümmern uns um die passende Offerte.</p>{button("Offerte anfragen")}</div></div></section>'
def breadcrumbs(label,parent=None):
 return '<div class="container breadcrumbs"><a href="/">Startseite</a><span aria-hidden="true">/</span>'+ (f'<a href="{parent[0]}">{parent[1]}</a><span aria-hidden="true">/</span>' if parent else '')+f'<span>{label}</span></div>'
def gallery():
 return '<section class="section muted"><div class="container">'+section_head('Einblicke in unsere Arbeit','Der Unterschied liegt im Detail.','Vorher und nachher: Aufnahmen aus unseren Reinigungsarbeiten.')+'<div class="results-grid">'+''.join(f'<article class="result"><div class="result-photos"><figure>{img(b,title+" vor der Reinigung")}<figcaption>Vorher</figcaption></figure><figure>{img(a,title+" nach der Reinigung")}<figcaption>Nachher</figcaption></figure></div><h3>{title}</h3></article>' for b,a,title in [('bath-before','bath-after','Badreinigung'),('drawer-before','drawer-after','Küchenreinigung')])+'</div></div></section>'
pages={}
def put(path,title,desc,body,label=None,kind='WebPage',service=None,faq_items=None,noindex=False):
 pages[path]=dict(title=title,desc=desc,body=body,label=label or title.split(' | ')[0],kind=kind,service=service,faq=faq_items,noindex=noindex)
put('/', 'Reinigungsfirma St. Gallen, Thurgau & Zürich | Ademi','Wohnungsreinigung, Endreinigung mit Abgabegarantie, Autoinnenreinigung und Polsterreinigung: St. Gallen, Thurgau und Zürich. Persönliche Offerte anfragen.',hero('St. Gallen · Thurgau · Zürich','Sauberkeit, die bleibt.\nService, der passt.','Für Ihr Zuhause, Ihr Auto und Ihre Lieblingsplätze. Ihr Reinigungsservice aus Rorschach für den Kanton St. Gallen, Thurgau und Zürich. Weitere Orte in der Schweiz auf Anfrage.','home')+'<div class="trust-strip"><div class="container"><span>Wohnungen & Häuser</span><span>Endreinigung mit Abgabegarantie</span><span>Auto & Polster</span><span>Regional für Sie da</span></div></div>'+'<section class="section"><div class="container">'+section_head('Für das, was Ihnen wichtig ist.','Ein Service. Viele saubere Lösungen.','Wählen Sie die Reinigung, die zu Ihrem Auftrag passt.', '<a class="text-link" href="/leistungen/">Alle Leistungen ↗</a>')+cards()+'</div></section>'+'<section class="quote-promo"><div class="container promo-grid"><div><span class="eyebrow">Autoinnenreinigung mit Online-Offerte</span><h2>Ihr Auto. Ihr Budget.<br>Ihr Preisvorschlag.</h2><p>Fahrzeug beschreiben, Fotos hinzufügen und Ihr Budget nennen. Sie sehen sofort einen nachvollziehbaren Vorschlag – die verbindliche Offerte bestätigen wir persönlich.</p>'+button('Preisvorschlag berechnen','/offerte/?leistung=auto')+'</div><div class="price-example"><span class="small-label">Ihre Online-Offerte</span><h3>Leistung auswählen.<br>Preis sehen.<br>Termine vorschlagen.</h3><p>Sie bestätigen die Angebotsübersicht. Den Auftrag und einen passenden Termin bestätigen wir persönlich.</p></div></div></section>'+process()+gallery()+'<div class="container project-link">'+button('Unsere Arbeit im Detail','/reinigungsprojekte/',True)+'</div>'+profile_section()+cta())
put('/leistungen/','Reinigungsleistungen in Rorschach | Dampfglanzservice-Ademi','Wohnungsreinigung, Endreinigung mit Abgabegarantie, Auto- und Polsterreinigung. Entdecken Sie unsere Leistungen in Rorschach und der Ostschweiz.',breadcrumbs('Leistungen')+hero('Unsere Leistungen','Für Räume. Für Fahrzeuge.\nFür ein gutes Gefühl.','Von der regelmässigen Wohnungsreinigung bis zur sorgfältigen Endreinigung: Wir stimmen den Auftrag auf Ihr Objekt und Ihre Wünsche ab.')+'<section class="section"><div class="container">'+cards()+'</div></section>'+process()+cta())
for key,s in services.items():
 s['desc']=s['desc']+' Anfragen aus St. Gallen, Thurgau und Zürich sind willkommen.';fa=s['faq'];body=breadcrumbs(s['label'],('/leistungen/','Leistungen'))+hero(s['tag'],s['title'],s['desc'],s['image'], 'Preisvorschlag berechnen' if key=='autoreinigung' else 'Offerte anfragen', '/offerte/?leistung=auto' if key=='autoreinigung' else f'/offerte/?leistung={key}')
 body+='<section class="section"><div class="container content-split"><div><span class="eyebrow">'+s['label']+'</span><h2>'+s['intro']+'</h2><p>'+s['body']+'</p></div><div class="scope-list">'+''.join(f'<article><span aria-hidden="true">✓</span><div><h3>{t}</h3><p>{d}</p></div></article>' for t,d in s['items'])+'</div></div></section>'

 if key in ['wohnungsreinigung','endreinigung-abnahmegarantie']:body+=gallery()
 body+=process()+faq(fa)+cta()
 put(f'/{key}/',s['label']+' in St. Gallen & Ostschweiz | '+NAME,s['desc'],body,service=s['label'],faq_items=fa)
regional_context={
'goldach':('Reinigung in direkter Nachbarschaft.','Goldach gehört zu unserem Einsatzgebiet rund um Rorschach. Ob Wohnung, Umzugsreinigung oder Autoinnenraum: Wir stimmen den Auftrag und die Anfahrt persönlich ab.','Für Wohnungen und Häuser in Goldach helfen uns Wohnfläche, Zimmerzahl und Fotos. Bei einem Umzug nennen Sie bitte zusätzlich den Termin der Wohnungsabgabe.'),
'rorschacherberg':('Persönlich für Rorschacherberg.','Für Reinigungsaufträge in Rorschacherberg ist unser Standort in Rorschach ein regionaler Ausgangspunkt. Wir besprechen die Arbeiten direkt mit Ihnen.','Geben Sie bei Ihrer Anfrage bitte Zugang, Stockwerk und Parkmöglichkeit an. Diese Angaben helfen, die Reinigung in Rorschacherberg passend zu planen.'),
'arbon':('Mehr Glanz in Arbon.','Wir nehmen Reinigungsanfragen aus Arbon entgegen: für Wohnräume, Endreinigungen, Fahrzeuge und Polster. Umfang und Termin werden individuell vereinbart.','Regelmässige Reinigung oder ein einzelner Auftrag? Beschreiben Sie Ihren Bedarf in Arbon und den gewünschten Rhythmus, damit wir eine passende Offerte erstellen können.'),
'steinach':('Saubere Lösungen für Steinach.','Auch in Steinach unterstützen wir Sie mit sorgfältiger Reinigung. Ein direkter Ansprechpartner begleitet Ihre Anfrage bis zum vereinbarten Auftrag.','Planen Sie eine Endreinigung in Steinach? Wohnfläche, Fenster und Storen sowie der Übergabetermin sind die wichtigsten Angaben für eine erste Einschätzung.'),
'horn':('Für Ihr Zuhause in Horn.','Für Kunden in Horn vereinbaren wir Wohnungs-, End-, Auto- und Polsterreinigungen nach Bedarf. Wir klären den Umfang vor der Ausführung.','Bei Polsterreinigungen in Horn senden Sie uns am besten Fotos sowie Material- und Grössenangaben. So können wir die Eignung und den Aufwand persönlich prüfen.'),
 'thal':('Reinigungsservice für Thal.','Von unserem Standort in Rorschach aus bearbeiten wir auch Anfragen aus Thal. Wir prüfen die Terminverfügbarkeit und besprechen die Anfahrt.','Für einen Auftrag in Thal nennen Sie bitte die vollständige Adresse und den gewünschten Termin. Besondere Zugangsbedingungen sollten wir vorab kennen.'),
 'staad':('Persönlicher Service für Staad.','Wohnung, Fahrzeug oder Polster: Für Aufträge in Staad stimmen wir die Reinigung auf Ihre Wünsche ab. Die Anfrage ist unverbindlich.','Bei der Autoinnenreinigung in Staad können Sie zuerst den Online-Preisvorschlag nutzen. Ort, Termin, Extras und eine allfällige Anfahrt werden danach bestätigt.'),
 'rheineck':('Saubere Arbeit für Rheineck.','Wir nehmen Reinigungsanfragen aus Rheineck entgegen und vereinbaren Leistungen, Termin und Anfahrt vor dem Auftrag.','Fotos von Küche, Bad und besonderen Verschmutzungen helfen bei Wohnungs- und Endreinigungen in Rheineck. Geben Sie ausserdem Wohnfläche und Zimmerzahl an.'),
 'st-margrethen':('Reinigung für St. Margrethen.','Für Aufträge in St. Margrethen planen wir den Einsatz individuell. Sprechen Sie mit uns über Ihr Objekt, Ihre Wünsche und Ihren Termin.','Wenn Sie eine Reinigung in St. Margrethen wünschen, teilen Sie uns bitte frühzeitig die Adresse und den Termin mit. Verfügbarkeit und Anfahrt werden persönlich bestätigt.')}
links=''.join(f'<a href="/reinigungsfirma-{k}/">{v}<span aria-hidden="true">↗</span></a>' for k,v in regions.items())
put('/regionen/','Reinigungsservice in der Ostschweiz | '+NAME,'Ihr Reinigungsservice aus Rorschach für Goldach, Rorschacherberg, Arbon, Steinach, Horn, Thal, Staad, Rheineck und St. Margrethen.',breadcrumbs('Regionen')+hero('Regional für Sie da','Hier zu Hause.\nIn der Region für Sie da.','Unser Standort ist Rorschach. Wir nehmen Anfragen aus der umliegenden Region und der Ostschweiz entgegen. Einsatzort, Verfügbarkeit und Anfahrt stimmen wir mit Ihnen ab.')+'<section class="section"><div class="container region-layout"><div class="region-anchor"><span class="eyebrow">Unser Ausgangspunkt</span><h2>Rorschach.</h2><p>Trischlistrasse 25<br>9400 Rorschach</p><span class="region-note">Am Bodensee zu Hause.</span></div><div class="region-links">'+links+'</div></div></section>'+faq([('Reinigen Sie auch in St. Gallen?','Ja, wir nehmen auch Anfragen aus St. Gallen und weiteren Teilen der Ostschweiz entgegen. Verfügbarkeit und Anfahrt bestätigen wir persönlich.'),('Ist die Anfahrt im Preis enthalten?','Eine allfällige Anfahrt wird mit der individuellen Offerte vereinbart. Im Online-Preisvorschlag für die Autoinnenreinigung ist sie nicht eingerechnet.')])+cta())
for key,city in regions.items():
 title,desc,tip=regional_context[key]
 body=breadcrumbs(city,('/regionen/','Regionen'))+hero('Ihr Reinigungsservice aus Rorschach',title,'Dampfglanzservice-Ademi für '+city+'. '+desc,'home')+'<section class="section"><div class="container content-split"><div><span class="eyebrow">Ihr Auftrag in '+city+'</span><h2>Gut geplant.<br>Sorgfältig gereinigt.</h2><p>'+tip+'</p></div><div class="note-card"><h3>Das hilft uns bei Ihrer Anfrage</h3><ul><li>Adresse und gewünschter Termin</li><li>Art und Umfang der Reinigung</li><li>Zustand und aussagekräftige Fotos</li><li>Besondere Wünsche und Ihr Budget</li></ul>'+button('Auftrag beschreiben')+'</div></div></section>'+'<section class="section muted"><div class="container">'+section_head('Unsere Leistungen in '+city,'Die passende Reinigung für Ihren Auftrag.')+cards()+'</div></section>'+cta()
 put('/reinigungsfirma-'+key+'/',f'Reinigungsfirma für {city} | {NAME}',f'Reinigungsservice für {city}: Wohnungs-, End-, Auto- und Polsterreinigung von Dampfglanzservice-Ademi aus Rorschach. Individuelle Offerte anfragen.',body,city,service='Reinigungsservice in '+city)
canton_data={
 'st-gallen':('St. Gallen','Vom Bodensee bis ins Rheintal und ins Toggenburg: Wir nehmen Reinigungsanfragen im ganzen Kanton St. Gallen entgegen. Unser einziger Standort ist Rorschach.','St. Gallen, Rorschach, Wil, Gossau, Altstätten, Buchs, Sargans und Rapperswil-Jona','Für eine Wohnungsübergabe nennen Sie den Abgabetermin und senden Fotos von Küche, Bad, Fenstern und Storen. Für regelmässige Unterstützung vereinbaren wir Aufgaben und Rhythmus.','Reinigungsfirma St. Gallen: Wohnungs- & Endreinigung'),
 'thurgau':('Thurgau','Sie suchen eine Reinigung im Thurgau? Von unserem Standort in Rorschach aus planen wir angefragte Einsätze am Bodensee und im weiteren Kanton individuell.','Arbon, Romanshorn, Amriswil, Frauenfeld, Kreuzlingen und Weinfelden','Bei Anfragen am Bodensee und im weiteren Thurgau helfen uns Adresse, Parkmöglichkeit und Zugang. Die Anfahrt wird vor dem Auftrag schriftlich vereinbart.','Reinigungsfirma Thurgau: Wohnungs- & Polsterreinigung'),
 'zuerich':('Zürich','Für Reinigung in Zürich und Winterthur prüfen wir Ihren Auftrag individuell. Auch für weitere Orte im Kanton Zürich können Sie uns eine Anfrage senden. Es gibt keine Niederlassung in Zürich.','Zürich, Winterthur, Uster, Dübendorf und weitere Orte im Kanton','Bei weiter entfernten Einsätzen prüfen wir Umfang, Termin und Anfahrt gemeinsam. Die Rorschacher Online-Pakete sind keine pauschale Preiszusage für einen Einsatz in Zürich.','Reinigungsfirma Zürich: Endreinigung & Wohnungsreinigung')}
for slug,(region,description,places,tip,title) in canton_data.items():
 body=breadcrumbs(region,('/regionen/','Regionen'))+hero('Reinigung im Kanton '+region,'Saubere Lösungen<br>für '+region+'.',description,'home')+'<section class="section"><div class="container content-split"><div><span class="eyebrow">Einsatzplanung</span><h2>Ihr Auftrag.<br>Gut vorbereitet.</h2><p>'+tip+'</p><p>Anfragen unter anderem aus '+places+'. Verfügbarkeit und Anfahrtskosten bestätigen wir vor dem Auftrag.</p></div><div class="note-card"><h3>Das brauchen wir für Ihre Offerte</h3><ul><li>Adresse, Wohnfläche oder Fahrzeug-/Polstergrösse</li><li>Gewünschte Arbeiten und Fotos des Zustands</li><li>Zwei mögliche Termine und Zugangshinweise</li></ul>'+button('Persönliche Offerte anfragen','/kontakt/')+'</div></div></section><section class="section muted"><div class="container">'+section_head('Unsere Leistungen für '+region,'Die passende Reinigung.')+cards()+'</div></section>'+faq([('Sind Sie vor Ort ansässig?','Unser Standort ist Rorschach. Einsätze in '+region+' werden individuell von dort aus geplant.'),('Wie erhalte ich einen Preis für meine Adresse?','Senden Sie uns die Adresse, den Umfang und Bilder. Sie erhalten eine persönliche Offerte inklusive vereinbarter Anfahrt.'),('Welche Reinigung kann ich anfragen?','Wohnungsreinigung, Umzugs- und Endreinigung mit vereinbarter Abgabegarantie, Autoinnenreinigung und Polsterreinigung.')])+cta()
 put('/reinigungsfirma-'+slug+'/',title+' | Ademi','Reinigung in '+region+': Wohnungs-, End-, Auto- und Polsterreinigung. Einsatz, Anfahrt und Termin persönlich vereinbaren. Offerte von Dampfglanzservice-Ademi.',body,region,service='Reinigungsservice '+region)
pages['/regionen/']['body']=pages['/regionen/']['body'].replace('<div class="region-links">','<div class="region-links">'+''.join('<a href="/reinigungsfirma-'+k+'/">Kanton '+v[0]+'<span aria-hidden="true">↗</span></a>' for k,v in canton_data.items()))
pages['/regionen/']['body']=pages['/regionen/']['body'].replace('Wir nehmen Anfragen aus der umliegenden Region und der Ostschweiz entgegen.','Wir nehmen Anfragen aus dem ganzen Kanton St. Gallen, Thurgau und Zürich entgegen. Weitere Schweizer Orte prüfen wir auf Anfrage.')
exec((ROOT/'tools/extra_pages.py').read_text())
put('/ueber-uns/','Über uns – Reinigungsservice aus Rorschach | '+NAME,'Dampfglanzservice-Ademi in Rorschach: persönlicher Kontakt, klare Vereinbarungen und sorgfältige Reinigung für Wohnungen, Autos und Polster.',breadcrumbs('Über uns')+hero('Dampfglanzservice-Ademi','Persönlich im Kontakt.\nGründlich in der Arbeit.','Hinter einer guten Reinigung stehen klare Absprachen und Menschen, die sich kümmern. Genau dafür steht unser Reinigungsservice aus Rorschach.','home')+'<section class="section"><div class="container content-split"><div><span class="eyebrow">Unser Anspruch</span><h2>Ihr Auftrag verdient<br>unsere Aufmerksamkeit.</h2><p>Wir besprechen Ihre Wünsche direkt mit Ihnen. Bevor die Arbeit beginnt, vereinbaren wir den Leistungsumfang und den Preis. Während der Reinigung achten wir auf Materialien, Details und die Besonderheiten Ihres Objekts.</p><p>Ob ein einzelner Auftrag oder regelmässige Unterstützung: Sie erhalten eine persönliche Lösung für Ihr Zuhause, Ihr Fahrzeug oder Ihre Polster.</p></div><div class="scope-list">'+''.join(f'<article><span aria-hidden="true">0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></article>' for i,(t,d) in enumerate([('Direkte Kommunikation','Ein persönlicher Ansprechpartner für Ihre Fragen und Vereinbarungen.'),('Klare Offerten','Leistungen und Preis werden vor dem Auftrag mit Ihnen abgestimmt.'),('Regional verbunden','Unser Standort ist Rorschach. Wir sind in der Ostschweiz für Sie da.')]))+'</div></div></section>'+gallery()+cta())
# Forms use the provider already present in the repository. No customer data is sent by previewing or calculating.
def form_meta(subject):return f'<input type="hidden" name="_subject" value="{subject}"><input type="hidden" name="_template" value="table"><input class="honeypot" type="text" name="_honey" tabindex="-1" autocomplete="off" aria-hidden="true"><input type="hidden" name="_autoresponse" value="Vielen Dank für Ihre Anfrage an Dampfglanzservice-Ademi. Wir prüfen Ihre Angaben persönlich. Erst unsere Bestätigung gilt als verbindliche Offerte.">'
def contact_fields():return '''<div class="field-grid"><div class="field"><label for="customer-name">Ihr Name <span>*</span></label><input id="customer-name" name="Name" autocomplete="name" maxlength="100" required></div><div class="field"><label for="customer-email">E-Mail <span>*</span></label><input id="customer-email" name="email" type="email" autocomplete="email" maxlength="160" required></div><div class="field"><label for="customer-phone">Telefon <span class="optional">optional</span></label><input id="customer-phone" name="Telefon" type="tel" autocomplete="tel" maxlength="40"></div><div class="field"><label for="customer-place">PLZ / Ort <span>*</span></label><input id="customer-place" name="Ort" autocomplete="address-level2" maxlength="120" required></div></div>'''
def consent():return '<label class="check consent"><input type="checkbox" name="Datenschutz" value="gelesen und Übermittlung zugestimmt" required><span>Ich habe die <a href="/datenschutz/" target="_blank" rel="noopener">Datenschutzhinweise</a> gelesen und stimme der Übermittlung meiner Angaben und ausgewählten Fotos zur Bearbeitung der Anfrage über FormSubmit zu. <span aria-hidden="true">*</span></span></label><p class="fine-print">Eine Anfrage ist keine Buchung. Preis, Leistungsumfang und Termin werden persönlich bestätigt. * Pflichtfelder</p>'
contact=breadcrumbs('Kontakt')+'<section class="section contact-section"><div class="container contact-layout"><div class="contact-intro"><span class="eyebrow">Wir sind für Sie da.</span><h1>Gute Reinigung<br>beginnt mit einem<br>guten Gespräch.</h1><p>Sie haben Fragen oder möchten einen Auftrag besprechen? Schreiben Sie uns oder rufen Sie direkt an.</p><div class="contact-lines"><div><span>Telefon</span><a href="tel:+41765024998">+41 76 502 49 98 ↗</a></div><div><span>E-Mail</span><a href="mailto:info@dampfglanzservice-ademi.ch">info@dampfglanzservice-ademi.ch ↗</a></div><div><span>Standort</span><p>Trischlistrasse 25 · 9400 Rorschach</p></div></div><div class="small-note">Sie möchten eine Autoinnenreinigung?<br><a href="/offerte/?leistung=auto">Direkt zum Online-Preisvorschlag ↗</a></div></div><div class="form-card"><span class="eyebrow">Ihre Anfrage</span><h2>Erzählen Sie uns davon.</h2><form action="https://formsubmit.co/info@dampfglanzservice-ademi.ch" method="POST" data-contact-form>'+form_meta('Neue Kontaktanfrage – Dampfglanzservice-Ademi')+contact_fields()+'<div class="field"><label for="contact-service">Gewünschte Leistung <span>*</span></label><select id="contact-service" name="Leistung" required><option value="">Bitte auswählen</option>'+''.join(f'<option>{s["label"]}</option>' for s in services.values())+'<option>Andere Anfrage</option></select></div><div class="field"><label for="message">Ihre Nachricht <span>*</span></label><textarea id="message" name="Nachricht" rows="5" maxlength="5000" required placeholder="Was dürfen wir reinigen? Wie gross ist das Objekt, und wann wünschen Sie den Termin?"></textarea></div>'+consent()+'<button class="button primary" type="submit">Anfrage senden <span aria-hidden="true">↗</span></button><p class="form-status" role="status"></p></form></div></div></section>'
put('/kontakt/','Kontakt & Reinigungsofferte in Rorschach | '+NAME,'Kontaktieren Sie Dampfglanzservice-Ademi in Rorschach. Telefon +41 76 502 49 98. Fragen zur Reinigung stellen oder unverbindliche Offerte anfragen.',contact,kind='ContactPage')
quote=breadcrumbs('Online-Offerte')+(ROOT/'tools/quote.template').read_text().replace('{{CONTACT}}',contact_fields()).replace('{{CONSENT}}',consent()).replace('{{META}}',form_meta('Bestätigte Angebotsanfrage – Dampfglanzservice-Ademi'))
put('/offerte/','Online-Offerte für Reinigung | '+NAME,'Reinigung auswählen, Fotos hinzufügen, Angebotspreis berechnen und zwei bis drei mögliche Termine angeben. Persönliche Auftragsbestätigung.',quote)
# Retain the existing legal statement text, remove repeated marketing/navigation and formatting artefacts.
from lxml import html as lhtml
for slug,label in [('impressum','Impressum'),('datenschutz','Datenschutz')]:
 original=lhtml.fromstring((ROOT/slug/'index.html').read_text())
 chunks=[]
 for section in original.xpath('//main/section'):
  if set(section.get('class','').split()) & {'hero','cta-section','contact-section'}:continue
  headings=section.xpath('.//h2')
  if not headings:continue
  content=[]
  for el in section.xpath('.//h3 | .//p | .//ul'):
   text=' '.join(el.text_content().split()).replace('```','')
   if text:content.append(f'<{el.tag}>'+(''.join('<li>'+esc(' '.join(li.text_content().split()))+'</li>' for li in el.xpath('./li')) if el.tag=='ul' else esc(text))+f'</{el.tag}>')
  chunks.append('<section class="legal-section"><h2>'+esc(' '.join(headings[0].text_content().split()))+'</h2>'+''.join(content)+'</section>')
 legal='<section class="section"><div class="container legal-content">'+''.join(chunks)
 if slug=='datenschutz':legal+='''<section class="legal-section"><h2>Online-Preisvorschlag und Foto-Anfragen</h2><p>Der Online-Preisvorschlag wird direkt in Ihrem Browser berechnet. Dabei werden weder Ihre Fotos noch Ihre Angaben automatisch übermittelt. Die Fotos werden nicht durch eine KI bewertet. Es gibt keine automatische Buchung und keinen verbindlichen Vertragsabschluss durch die Berechnung.</p><p>Beim bewussten Absenden der Offertenanfrage werden die von Ihnen eingegebenen Kontaktangaben, Auftragsdetails, Ihr Budget, die Berechnungsübersicht und ausgewählte Bilder über den bereits verwendeten Dienst FormSubmit an info@dampfglanzservice-ademi.ch übermittelt. FormSubmit kann Sie für den Spam-Schutz zu einer reCAPTCHA-Prüfung weiterleiten. Mehr über den Dienst erfahren Sie in den <a href="https://formsubmit.co/privacy.pdf" target="_blank" rel="noopener">Datenschutzhinweisen von FormSubmit</a>.</p><p>Laden Sie nur auftragsbezogene Fotos hoch und vermeiden Sie Personen, Kennzeichen und vertrauliche Unterlagen. Ihre Angaben werden zur Bearbeitung der Anfrage und Erstellung einer persönlichen Offerte verwendet. Fragen zu Ihren Daten und Löschungswünsche können Sie an unsere oben genannte E-Mail-Adresse richten.</p><p>Die Foto-Vorschau und Eingaben werden durch diese Website nicht dauerhaft im Browser gespeichert. Eine Anfrage wird als E-Mail verarbeitet. Gesetzliche Aufbewahrungspflichten bleiben vorbehalten.</p></section>'''
 legal+='</div></section>'
 put('/'+slug+'/',label+' | '+NAME,label+' und Unternehmensangaben von Dampfglanzservice-Ademi in Rorschach. Informationen zu Kontakt, Website und Offertenanfragen.',breadcrumbs(label)+'<section class="text-hero"><div class="container"><span class="eyebrow">Dampfglanzservice-Ademi</span><h1>'+label+'</h1><p class="legal-lead">Unternehmensangaben und Informationen zur Nutzung unserer Website.</p></div></section>'+legal)
# Idempotent legal pages: save original text data outside generated pages for subsequent builds.
legal_cache=ROOT/'tools/legal_content.json'
if legal_cache.exists():
 cached=json.loads(legal_cache.read_text())
 for slug,body in cached.items():pages['/'+slug+'/']['body']=body
else:legal_cache.write_text(json.dumps({slug:pages['/'+slug+'/']['body'] for slug in ['impressum','datenschutz']},ensure_ascii=False,indent=2))
project_body=breadcrumbs('Reinigungsprojekte')+hero('Echte Aufnahmen aus unserer Arbeit','Sauberkeit sehen.<br>Arbeit nachvollziehen.','Unsere vorhandenen Projektbilder zeigen Bad- und Küchenreinigung. Wir verwenden diese Aufnahmen als Einblicke in unsere Arbeit. Das Ergebnis eines neuen Auftrags hängt vom Material, Zustand und vereinbarten Umfang ab.')+'<section class="section"><div class="container">'+gallery().replace('<section class="section muted"><div class="container">','').replace('</div></section>','')+'</div></section><section class="section"><div class="container content-split"><div><span class="eyebrow">Vor dem Auftrag</span><h2>Ein Bild hilft.<br>Klare Angaben helfen mehr.</h2><p>Zeigen Sie zuerst den gesamten Bereich und danach die betroffenen Stellen aus der Nähe. Geben Sie Material, bisherige Behandlungen und Ihre wichtigsten Wünsche an. Wir beurteilen die Informationen persönlich; Fotos werden nicht automatisch von einer KI ausgewertet.</p><p>Eine Reinigung kann Verschmutzungen behandeln. Kratzer, beschädigte Beschichtungen und Materialveränderungen sind andere Themen und gehören nicht zu einer pauschalen Reinigungszusage.</p></div><div class="note-card"><h3>So fotografieren Sie Ihren Auftrag</h3><ul><li>Ein Übersichtsbild bei guter Beleuchtung</li><li>Ein Detailbild von Flecken oder Ablagerungen</li><li>Ein Bild vom Materialetikett, falls vorhanden</li><li>Keine Personen oder vertraulichen Dokumente zeigen</li></ul>'+button('Fotos zur Offerte hinzufügen','/offerte/')+'</div></div></section>'+cta()
put('/reinigungsprojekte/','Reinigungsprojekte: Bad & Küche vorher/nachher | Ademi','Echte Bilder von Bad- und Küchenreinigung. Sehen Sie Einblicke in unsere Arbeit und erfahren Sie, welche Fotos bei Ihrer Reinigungsanfrage helfen.',project_body)
put('/bewertungen/','Google-Kundenbewertungen | Dampfglanzservice-Ademi','Elf echte Google-Bewertungen mit Namen, originalen Zeitangaben und kurzen Auszügen. Quellen prüfen und Dampfglanzservice-Ademi kennenlernen.',reviews_page())
put('/404.html','Seite nicht gefunden | '+NAME,'Diese Seite wurde nicht gefunden. Entdecken Sie unsere Reinigungsleistungen oder kontaktieren Sie Dampfglanzservice-Ademi.','<section class="text-hero"><div class="container"><span class="eyebrow">404 · Seite nicht gefunden</span><h1>Hier fehlt etwas.<br>Glanz gibt es trotzdem.</h1><p>Diese Adresse ist nicht verfügbar. Finden Sie auf der Startseite die passende Reinigung.</p>'+button('Zur Startseite','/')+'</div></section>',noindex=True)
for path,p in pages.items():
 url=BASE+path
 business={'@type':'LocalBusiness','@id':BASE+'/#business','name':NAME,'logo':BASE+'/assets/brand.png','url':BASE+'/','telephone':'+41765024998','email':'info@dampfglanzservice-ademi.ch','image':BASE+'/assets/brand.png','address':{'@type':'PostalAddress','streetAddress':'Trischlistrasse 25','postalCode':'9400','addressLocality':'Rorschach','addressCountry':'CH'},'identifier':'CHE-199.157.071','areaServed':['Rorschach','Kanton St. Gallen','Thurgau','Kanton Zürich']+list(regions.values()),'sameAs':['https://share.google/dCGFMFzPosnnV46j6']}
 graph=[business,{'@type':'WebSite','@id':BASE+'/#website','name':NAME,'url':BASE+'/'},{'@type':p['kind'],'@id':url+'#page','name':p['title'],'description':p['desc'],'url':url,'inLanguage':'de-CH','isPartOf':{'@id':BASE+'/#website'}}]
 if path!='/' and path!='/404.html':graph.append({'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Startseite','item':BASE+'/'},{'@type':'ListItem','position':2,'name':p['label'],'item':url}]})
 if p['service']:graph.append({'@type':'Service','name':p['service'],'provider':{'@id':BASE+'/#business'},'areaServed':p['label'] if path.startswith('/reinigungsfirma') else ['Kanton St. Gallen','Thurgau','Kanton Zürich'],'url':url})
 schema=json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('</','<\\/')
 html=f'''<!doctype html><html lang="de-CH"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(p['title'])}</title><meta name="description" content="{esc(p['desc'],quote=True)}"><meta name="robots" content="{'noindex,follow' if p['noindex'] else 'index,follow'}"><meta name="theme-color" content="#ffffff"><meta name="google-site-verification" content="Q_Ead2BqWl0n4IqW6wstFdwtrNm8mLhezZjtmdLTUcU"><link rel="canonical" href="{url}"><link rel="icon" href="/assets/brand.png" type="image/png"><meta property="og:type" content="website"><meta property="og:locale" content="de_CH"><meta property="og:site_name" content="{NAME}"><meta property="og:title" content="{esc(p['title'])}"><meta property="og:description" content="{esc(p['desc'],quote=True)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{BASE}/assets/home.webp"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/style.css?v=20261009f">{('<script defer src="/pricing.js?v=20261009f"></script>' if path=='/offerte/' else '')}<script defer src="/script.js?v=20261009f"></script><script type="application/ld+json">{schema}</script></head><body id="top">{header(path)}<main id="main">{p['body']}</main>{footer()}{quick_contact()}</body></html>'''
 target=ROOT/(path.strip('/')+'/index.html' if path.endswith('/') and path!='/' else 'index.html' if path=='/' else path.lstrip('/'));target.parent.mkdir(parents=True,exist_ok=True);target.write_text(lhtml.tostring(lhtml.fromstring(html),encoding="unicode",pretty_print=True,doctype="<!doctype html>"))
urls=[BASE+p for p,d in pages.items() if not d['noindex']]
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in urls)+'</urlset>')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /tools/\nSitemap: '+BASE+'/sitemap.xml\n')
print(f'Built {len(pages)} pages; all existing routes retained.')
