# Executed by build_site with the shared page components in scope.
areas=json.loads((ROOT/'tools/regional_content.json').read_text())
area_links=''
for a in areas:
 path='/reinigung-'+a['slug']+'/'
 related=''.join('<a class="button secondary" href="/'+k+'/">'+services[k]['label']+' ↗</a>' for k in a['related'])
 body=breadcrumbs(a['name'],('/regionen/','Regionen'))+hero('Ostschweiz · Einsatz auf Anfrage','Reinigung für<br>'+a['name']+'.',a['intro'])
 body+='<section class="section"><div class="container content-split"><div><span class="eyebrow">Ihr Auftrag im Detail</span><h2>'+a['focus']+'</h2><p>'+a['text']+'</p></div><div class="note-card"><h3>So wird Ihre Anfrage aussagekräftig</h3><ul>'+''.join('<li>'+v+'</li>' for v in a['check'])+'</ul>'+button('Details zur Offerte senden','/kontakt/')+'</div></div></section>'
 body+='<section class="section muted"><div class="container">'+section_head('Passende Leistungen','Was möchten Sie reinigen lassen?')+'<div class="hero-actions">'+related+'</div></div></section>'
 body+=faq([(a['question'],a['answer']),('Wie wird die Anfahrt vereinbart?','Unser Betrieb sitzt in Rorschach. Für diesen Einsatz klären wir Anfahrt, Gesamtpreis und Termin schriftlich, bevor Sie den Auftrag bestätigen.')])+cta()
 put(path,'Reinigung '+a['name']+' | Dampfglanzservice-Ademi','Reinigungsanfrage für '+a['name']+': '+a['focus']+'. Leistungen, Anfahrt und Termine persönlich vereinbaren.',body,a['name'],service='Reinigung '+a['name'])
 area_links+='<article class="area-card"><span class="small-label">Einsatz auf Anfrage</span><h3>'+a['name']+'</h3><p>'+a['focus']+'.</p><a class="text-link" href="'+path+'">Auftrag vorbereiten ↗</a></article>'
pages['/regionen/']['body']=pages['/regionen/']['body'].replace('</section>'+faq([('Reinigen Sie auch in St. Gallen?','Ja, wir nehmen auch Anfragen aus St. Gallen und weiteren Teilen der Ostschweiz entgegen. Verfügbarkeit und Anfahrt bestätigen wir persönlich.'),('Ist die Anfahrt im Preis enthalten?','Eine allfällige Anfahrt wird mit der individuellen Offerte vereinbart. Im Online-Preisvorschlag für die Autoinnenreinigung ist sie nicht eingerechnet.')]),'</section><section class="section muted"><div class="container">'+section_head('Weitere Gebiete in der Ostschweiz','Regional planen. Persönlich abstimmen.','Unser einziger Standort ist Rorschach. Weiter entfernte Einsätze bestätigen wir nach Prüfung von Umfang, Anfahrt und Verfügbarkeit.')+'<div class="area-cards">'+area_links+'</div></div></section>')
pages['/regionen/']['desc']='Reinigung in St. Gallen, Thurgau, Appenzell, Schaffhausen, Glarus und Graubünden sowie Zürich. Einsatz und Anfahrt aus Rorschach individuell anfragen.'
combo=breadcrumbs('Kombireinigung',('/leistungen/','Leistungen'))+hero('Wohnung · Auto · Polster','Mehrere Wünsche.<br>Eine klare Offerte.','Sie möchten Wohnung und Sofa, Auto und Polster oder mehrere Räume gemeinsam reinigen lassen? Beschreiben Sie jede gewünschte Leistung in einer Anfrage. Wir prüfen Umfang, Material und Einsatzplanung.')+'<section class="section"><div class="container content-split"><div><h2>Jede Leistung klar abgegrenzt.</h2><p>Eine Kombination soll Ihre Planung vereinfachen. Sie ist kein automatisch rabattiertes Paket. Wir halten fest, welche Arbeiten an welchem Objekt erfolgen, wo gereinigt wird und ob die Ausführung am selben Tag möglich ist.</p><p>Für eine Wohnungsreinigung nennen Sie Räume und Fläche. Bei einem Fahrzeug brauchen wir Modell, Grösse und Zustand. Für ein Sofa sind Sitzplätze, Material und Fotos hilfreich. Ergänzen Sie ein Gesamtbudget und zwei mögliche Termine.</p></div><div class="note-card"><h3>Ihre Anfrage in vier Punkten</h3><ul><li>Leistungen einzeln nennen</li><li>Jedes Objekt mit Fotos beschreiben</li><li>Einsatzort und Zugang mitteilen</li><li>Budget und Termine vorschlagen</li></ul>'+button('Kombireinigung anfragen','/offerte/?leistung=other')+'</div></div></section>'+faq([('Gibt es einen automatischen Kombirabatt?','Nein. Wir prüfen den gemeinsamen Auftrag und bieten die Leistungen transparent an. Ein Nachlass gilt nur, wenn er ausdrücklich in Ihrer Offerte vereinbart ist.'),('Kann alles an einem Tag erledigt werden?','Das hängt von Umfang, Material, Trocknungszeiten und Verfügbarkeit ab. Wir bestätigen den Ablauf vor dem Auftrag.')])+cta()
put('/kombireinigung/','Kombireinigung: Wohnung, Auto & Sofa | Ademi','Wohnung, Auto und Polster gemeinsam reinigen lassen: individuelle Kombireinigung mit klaren Leistungen, Preis und Termin. Anfrage mit Fotos senden.',combo,service='Kombireinigung')
pages['/leistungen/']['body']=pages['/leistungen/']['body'].replace('</section>'+process(),'</section><section class="section muted"><div class="container">'+section_head('Individuell kombinieren','Wohnung, Auto und Sofa gemeinsam anfragen.','Mehrere Leistungen werden in einer persönlichen Offerte mit klaren Bestandteilen angeboten.')+button('Kombireinigung entdecken','/kombireinigung/')+'</div></section>'+process())
